// Code generated
// This file is a generated precompile contract config with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package verify

import (
	"errors"
	"fmt"
	"math/big"

	"github.com/ava-labs/subnet-evm/accounts/abi"
	"github.com/ava-labs/subnet-evm/precompile/contract"
	"github.com/ava-labs/subnet-evm/vmerrs"

	_ "embed"

	"github.com/ethereum/go-ethereum/common"
)

const (
	// Gas costs for each function. These are set to 1 by default.
	// You should set a gas cost for each function in your contract.
	// Generally, you should not set gas costs very low as this may cause your network to be vulnerable to DoS attacks.
	// There are some predefined gas costs in contract/utils.go that you can use.
	VerifyProofGasCost       uint64 = 100000000 /* SET A GAS COST HERE */
	VerifyPublicInputGasCost uint64 = 100000000 /* SET A GAS COST HERE */
)

// CUSTOM CODE STARTS HERE
// Reference imports to suppress errors from unused imports. This code and any unnecessary imports can be removed.
var (
	_ = abi.JSON
	_ = errors.New
	_ = big.NewInt
)

// Singleton StatefulPrecompiledContract and signatures.
var (

	// VerifyRawABI contains the raw ABI of Verify contract.
	//go:embed contract.abi
	VerifyRawABI string

	VerifyABI = contract.ParseABI(VerifyRawABI)

	VerifyPrecompile = createVerifyPrecompile()
)

type VerifyProofInput struct {
	Proof             []*big.Int
	Inputs            []*big.Int
	VerificationKeyId [32]byte
}

type VerifyPublicInputInput struct {
	Inputs []*big.Int
	P      *big.Int
}

// UnpackVerifyProofInput attempts to unpack [input] as VerifyProofInput
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackVerifyProofInput(input []byte) (VerifyProofInput, error) {
	inputStruct := VerifyProofInput{}
	err := VerifyABI.UnpackInputIntoInterface(&inputStruct, "verifyProof", input)

	return inputStruct, err
}

// PackVerifyProof packs [inputStruct] of type VerifyProofInput into the appropriate arguments for verifyProof.
func PackVerifyProof(inputStruct VerifyProofInput) ([]byte, error) {
	return VerifyABI.Pack("verifyProof", inputStruct.Proof, inputStruct.Inputs, inputStruct.VerificationKeyId)
}

// PackVerifyProofOutput attempts to pack given result of type bool
// to conform the ABI outputs.
func PackVerifyProofOutput(result bool) ([]byte, error) {
	return VerifyABI.PackOutput("verifyProof", result)
}

func verifyProof(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, VerifyProofGasCost); err != nil {
		return nil, 0, err
	}
	if readOnly {
		return nil, remainingGas, vmerrs.ErrWriteProtection
	}
	// attempts to unpack [input] into the arguments to the VerifyProofInput.
	// Assumes that [input] does not include selector
	// You can use unpacked [inputStruct] variable in your code
	inputStruct, err := UnpackVerifyProofInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	// CUSTOM CODE STARTS HERE
	_ = inputStruct // CUSTOM CODE OPERATES ON INPUT

	var output bool // CUSTOM CODE FOR AN OUTPUT
	packedOutput, err := PackVerifyProofOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// UnpackVerifyPublicInputInput attempts to unpack [input] as VerifyPublicInputInput
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackVerifyPublicInputInput(input []byte) (VerifyPublicInputInput, error) {
	inputStruct := VerifyPublicInputInput{}
	err := VerifyABI.UnpackInputIntoInterface(&inputStruct, "verifyPublicInput", input)

	return inputStruct, err
}

// PackVerifyPublicInput packs [inputStruct] of type VerifyPublicInputInput into the appropriate arguments for verifyPublicInput.
func PackVerifyPublicInput(inputStruct VerifyPublicInputInput) ([]byte, error) {
	return VerifyABI.Pack("verifyPublicInput", inputStruct.Inputs, inputStruct.P)
}

// PackVerifyPublicInputOutput attempts to pack given result of type bool
// to conform the ABI outputs.
func PackVerifyPublicInputOutput(result bool) ([]byte, error) {
	return VerifyABI.PackOutput("verifyPublicInput", result)
}

func verifyPublicInput(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, VerifyPublicInputGasCost); err != nil {
		return nil, 0, err
	}
	if readOnly {
		return nil, remainingGas, vmerrs.ErrWriteProtection
	}
	// attempts to unpack [input] into the arguments to the VerifyPublicInputInput.
	// Assumes that [input] does not include selector
	// You can use unpacked [inputStruct] variable in your code
	inputStruct, err := UnpackVerifyPublicInputInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	// CUSTOM CODE STARTS HERE
	_ = inputStruct // CUSTOM CODE OPERATES ON INPUT

	var output bool = true  // CUSTOM CODE FOR AN OUTPUT
	for _,input := range inputStruct.Inputs {
		if input.Cmp(inputStruct.P) != -1 {
			fmt.Errorf("verifier-gte-snark-scalar-field")
			output = false	
		}   
	}

	packedOutput, err := PackVerifyPublicInputOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// createVerifyPrecompile returns a StatefulPrecompiledContract with getters and setters for the precompile.

func createVerifyPrecompile() contract.StatefulPrecompiledContract {
	var functions []*contract.StatefulPrecompileFunction

	abiFunctionMap := map[string]contract.RunStatefulPrecompileFunc{
		"verifyProof":       verifyProof,
		"verifyPublicInput": verifyPublicInput,
	}

	for name, function := range abiFunctionMap {
		method, ok := VerifyABI.Methods[name]
		if !ok {
			panic(fmt.Errorf("given method (%s) does not exist in the ABI", name))
		}
		functions = append(functions, contract.NewStatefulPrecompileFunction(method.ID, function))
	}
	// Construct the contract with no fallback function.
	statefulContract, err := contract.NewStatefulPrecompileContract(nil, functions)
	if err != nil {
		panic(err)
	}
	return statefulContract
}
